name: Generate and Deploy Client Libraries

on:
  push:
    branches:
      - main

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    outputs:
      repo_prefix: ${{ steps.repo_prefix.outputs.prefix }}
    steps:
      - uses: actions/checkout@main

      - name: Determine Repo Prefix
        id: repo_prefix
        run: echo "prefix=$(echo "$GITHUB_REPOSITORY" | sed 's/.*\///' | sed 's/-Docs\|-Declaration\|-Documentation//')" >> $GITHUB_OUTPUT


  generate-and-deploy-http-libs:
    needs: setup-environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@main

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install jq -y

      - name: Set up JDK 11
        uses: actions/setup-java@main
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Find API Specifications
        id: find_specs
        run: echo "spec_paths=$(find openapi -type f \( -iname "*.yaml" -o -iname "*.json" \) | xargs)" >> $GITHUB_OUTPUT

      - name: Generate Clients
        run: |
          mkdir -p generated-clients
          spec_paths=${{ steps.find_specs.outputs.spec_paths }}
          repo_prefix=${{ needs.setup-environment.outputs.repo_prefix }}
          wget https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/5.3.0/openapi-generator-cli-5.3.0.jar -O openapi-generator-cli.jar
          for spec in $spec_paths; do
            filename=$(basename "${spec%.*}" | sed 's/\.swagger$//')
            for generator in go python dart-dio typescript-axios; do
              library_name="${repo_prefix}-${filename}-${generator}-http-library"
              output_dir="generated-clients/$library_name"
              mkdir -p "$output_dir"
              echo "Generating $generator client for $spec"
              java -jar openapi-generator-cli.jar generate -i "$spec" -g "$generator" -o "$output_dir"
            done
          done

      - name: Customize package.json for TypeScript Axios
        run: |
          spec_paths=${{ steps.find_specs.outputs.spec_paths }}
          repo_prefix=${{ needs.setup-environment.outputs.repo_prefix }}
          for spec in $spec_paths; do
            filename=$(basename "${spec%.*}" | sed 's/\.swagger$//')
            ts_library_dir="generated-clients/${repo_prefix}-${filename}-typescript-axios-http-library"
            if [ -d "$ts_library_dir" ]; then
              cd "$ts_library_dir"
              if [ -f "package.json" ]; then
                jq --arg url "https://github.com/${{ github.repository_owner }}/${repo_prefix}-${filename}-typescript-axios-http-library.git" '.repository = {"type": "git", "url": $url}' package.json > temp.json && mv temp.json package.json
              else
                jq -n --arg name "${repo_prefix}-${filename}-typescript-axios-http-library" --arg url "https://github.com/${{ github.repository_owner }}/${repo_prefix}-${filename}-typescript-axios-http-library.git" '{"name": $name, "version": "1.0.0", "description": "TypeScript Axios client generated from OpenAPI spec", "main": "index.js", "scripts": {"build": "tsc"}, "author": "", "license": "ISC", "dependencies": {"axios": "^0.21.1"}, "repository": {"type": "git", "url": $url}}' > package.json
              fi
              cd -
            fi
          done

      - name: Create and Push Repositories
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          chmod +x scripts/manage-repo.sh
          spec_paths=${{ steps.find_specs.outputs.spec_paths }}
          commit_message=$(git log -1 --pretty=%B)
          repo_prefix=${{ needs.setup-environment.outputs.repo_prefix }}
          for spec in $spec_paths; do
            filename=$(basename "${spec%.*}" | sed 's/\.swagger$//')
            for generator in go python dart-dio typescript-axios; do
              library_name="${repo_prefix}-${filename}-${generator}-http-library"
              output_dir="generated-clients/$library_name"
              scripts/manage-repo.sh "$library_name" "$output_dir" "$commit_message"
            done
          done

  generate-and-deploy-grpc-libs:
    needs: setup-environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@main
        with:
         submodules: "recursive"


      - name: Set up Go
        uses: actions/setup-go@main
        with:
          go-version: '^1.16'

      - name: Set up Dart
        uses: dart-lang/setup-dart@main
        with:
          sdk: "stable"

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: '3.x'

      - name: Setup Protobuf and Plugins
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest
          pip install grpcio-tools grpcio
          dart pub global activate protoc_plugin
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

          

      - name: Find Proto Specifications
        id: find_protos
        run: echo "proto_paths=$(find proto -type f -iname "*.proto" | xargs)" >> $GITHUB_OUTPUT

      - name: Generate gRPC Clients and Servers
        run: |
          mkdir -p generated-grpc-libs/{dart,go,python}
          proto_paths=${{ steps.find_protos.outputs.proto_paths }}
          proto_include="-I proto -I vendor/googleapis -I vendor/grpc-gateway"
          for proto in $proto_paths; do 
            protoc \
              $proto_include \
              --dart_out generated-grpc-libs/dart \
              --go_out generated-grpc-libs/go  \
              --go_opt paths=source_relative \
              --go-grpc_out generated-grpc-libs/go  \
              --go-grpc_opt paths=source_relative \
              --grpc-gateway_out generated-grpc-libs/go) \
              --grpc-gateway_opt paths=source_relative \
              "$proto"
          done

      - name: Create and Push Repositories for gRPC
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          chmod +x scripts/manage-repo.sh
          repo_prefix=${{ needs.setup-environment.outputs.repo_prefix }}
          commit_message=$(git log -1 --pretty=%B)
          proto_paths=${{ steps.find_protos.outputs.proto_paths }}
          for proto in $proto_paths; do
            filename=$(basename "${proto%.*}")
            for lang in dart go python; do
              library_name="${repo_prefix}-${filename}-${lang}-grpc-library"
              output_dir="generated-grpc-libs/$lang/$library_name"
              # This script should handle checking, updating, or creating repositories
              scripts/manage-repo.sh "$library_name" "$output_dir" "$commit_message"
            done
          done
